_{Hello,

Thank you for requesting a password reset for your 
%application_name account.

This request was generated by submiting the "User name & password reminder"
form.

To initiate the password reset process, please click the following link:
%password_reset_url

If clicking the link above does not work, copy and paste the URL in a
new browser window instead. The URL will expire in 24 hours for
security reasons.

If you did not request a password reset, then please disregard this
email.

This is an automatically generated message. Replies are not monitored
or answered.

Sincerely,

The %application_name Team
}