#!/usr/bin/env php
<?php

define('MAKELOS_STANDALONE', true);
// define('AK_BASE_DIR', '/path/to/an/akelos/app');

defined('DS') || define('DS', DIRECTORY_SEPARATOR);
define('AK_BASE_DIR', $_SERVER['PWD']);
defined('AK_FRAMEWORK_DIR') || define('AK_FRAMEWORK_DIR', AK_BASE_DIR.DS.'vendor'.DS.'akelos');
define('MAKELOS_BASE_DIR', dirname(__FILE__));
defined('AK_TEST_DIR') || define('AK_TEST_DIR', MAKELOS_BASE_DIR.DS.'test');
define('AK_TESTING_NAMESPACE', 'plugins');

$GLOBALS['argv'][] = '--component=plugins';

include AK_FRAMEWORK_DIR.DS.'akelos_utils'.DS.'makelos'.DS.'makelos.php';

